<a href="https://colab.research.google.com/github/HariPrasad017/IIP_AIMLTN_ASSESMENT/blob/main/HariPrasad_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

data = np.array([
    [22.5, 19.0, 31.2, 28.7, 25.1],
    [17.3, 22.8, 30.5, 26.4, 21.9],
    [33.1, 29.6, 18.4, 24.0, 27.8],
    [20.2, 23.5, 31.9, 28.1, 22.6]
])

print("Temperature Data:\n", data)


# -----------------------------
# Task 1
# -----------------------------
print("\nShape of data:", data.shape)

mean_per_station = np.mean(data, axis=1)

print("\nMean temperature per station:")
print(mean_per_station)


# -----------------------------
# Task 2
# -----------------------------

mask = data > 28.0

temps_above_28 = data[mask]

print("\nTemperature readings above 28.0°C:")
print(temps_above_28)


# -----------------------------
# Task 3
# -----------------------------

normalized = (data - data.min()) / (data.max() - data.min())

normalized_rounded = np.round(normalized, 2)

print("\nNormalized Temperature Data (0 to 1 range):")
print(normalized_rounded)

Temperature Data:
 [[22.5 19.  31.2 28.7 25.1]
 [17.3 22.8 30.5 26.4 21.9]
 [33.1 29.6 18.4 24.  27.8]
 [20.2 23.5 31.9 28.1 22.6]]

Shape of data: (4, 5)

Mean temperature per station:
[25.3  23.78 26.58 25.26]

Temperature readings above 28.0°C:
[31.2 28.7 30.5 33.1 29.6 31.9 28.1]

Normalized Temperature Data (0 to 1 range):
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
